module.exports = class CommandBuilder {
  constructor() {
    this.commands = {
      "getTempAbgas": null,
      "getTempKsoll": null,
      "getBrennerStatus": null,
      "getNeigungM1": null,
      "getNeigungM2": null,
      "getNiveauM1": null,
      "getNiveauM2": null,
      "setNeigungM1": null,
      "setNeigungM2": null,
      "setNiveauM1": null,
      "setNiveauM2": null,
      "getTempVListM1": null,
      "getTempVListM2": null,
      "getTempRL17A": null,
      "getPumpeStatusM1": null,
      "getPumpeStatusM2": null,
      "getPumpeDrehzahlM2": null,
      "getPumpeStatusIntern": null,
      "getPumpeDrehzahlIntern": null,
      "getPumpeStatusSp": null,
      "getPumpeStatusZirku": null,
      "getPumpeDrehzahlSolar": null,
      "getMischerM2": null,
      "getStatusStoerung": null,
      "get": null,
      "getTempA": null,
      "getTempAtp": null,
      "getTempAged": null,
      "getTempWWist": null,
      "getTempWWsoll": null,
      "setTempWWsoll": null,
      "getTempStp2": null,
      "getWWUWPNachlauf": null,
      "setWWUWPNachlauf": null,
      "getSpeichervorrang": null,
      "setSpeichervorrang": null,
      "getSpeichervorrangM2": null,
      "setSpeichervorrangM2": null,
      "getSpeichervorrangM3": null,
      "setSpeichervorrangM3": null,
      "getTempKOffset": null,
      "setTempKOffset": null,
      "getTempKist": null,
      "getTempKtp": null,
      "getVolStrom": null,
      "getBetriebszeitStandby": null,
      "getBrennerStatus2": null,
      "getBrennerStufe": null,
      "getBrennerStarts": null,
      "setBrennerStarts": null,
      "getBrennerStunden1": null,
      "setBrennerStunden1": null,
      "getBrennerStunden2": null,
      "getLeistungIst": null,
      "getOeldurchsatz": null,
      "setOeldurchsatz": null,
      "getOelverbrauch": null,
      "getTempVLsollM1": null,
      "getTempVLsollM2": null,
      "getTempVLsollM3": null,
      "getTempKol": null,
      "getSolarStatusWW": null,
      "getSolarStunden": null,
      "getSolarLeistung": null,
      "getTempS4": null,
      "getTempSpu": null,
      "getTempStp": null,
      "getTempRaumNorSollM1": null,
      "setTempRaumNorSollM1": {"^(\\d+)$": {"getTempRaumNorSollM1": "$1.0000 Grad Celsius"}},
      "getTempRaumNorSollM2": null,
      "setTempRaumNorSollM2": null,
      "getTempRaumRedSollM1": null,
      "setTempRaumRedSollM1": {"^(\\d+)$": {"getTempRaumRedSollM1": "$1.0000 Grad Celsius"}},
      "getTempRaumRedSollM2": null,
      "setTempRaumRedSollM2": null,
      "getPumpeStatusSolar": null,
      "getPumpeStatusSolar2": null,
      "getPumpeStatusSolar3": null,
      "getPumpeStatusSolar4": null,
      "getTempSTSSOL": null,
      "getMischerM1": null,
      "getMischerM3": null,
      "getTimerM1Mo": null,
      "getTimerM1Di": null,
      "getTimerM1Mi": null,
      "getTimerM1Do": null,
      "getTimerM1Fr": null,
      "getTimerM1Sa": null,
      "getTimerM1So": null,
      "getTimerM2Mo": null,
      "getTimerM2Di": null,
      "getTimerM2Mi": null,
      "getTimerM2Do": null,
      "getTimerM2Fr": null,
      "getTimerM2Sa": null,
      "getTimerM2So": null,
      "getTimerWWMo": null,
      "getTimerWWDi": null,
      "getTimerWWMi": null,
      "getTimerWWDo": null,
      "getTimerWWFr": null,
      "getTimerWWSa": null,
      "getTimerWWSo": null,
      "getTimerZirkuMo": null,
      "getTimerZirkuDi": null,
      "getTimerZirkuMi": null,
      "getTimerZirkuDo": null,
      "getTimerZirkuFr": null,
      "getTimerZirkuSa": null,
      "getTimerZirkuSo": null,
      "getBetriebArtM1": null,
      "getBetriebArt": null,
      "getBetriebArtM2": null,
      "getBetriebSparM1": null,
      "getBetriebSparM2": null,
      "getBetriebPartyM1": null,
      "getBetriebPartyM2": null,
      "getTempPartyM1": null,
      "setTempPartyM1": null,
      "getTempPartyM2": null,
      "setTempPartyM2": null,
      "setBetriebPartyM1": null,
      "setBetriebPartyM2": null,
      "getEinflussExtSperren": null,
      "getEinflussExtAnforderung": null,
      "getExtSperren": null,
      "getExtAnforderung": null,
      "getStatusFrostM1": null,
      "getStatusFrostM2": null,
      "getError0": null,
      "getError1": null,
      "getError2": null,
      "getError3": null,
      "getError4": null,
      "getError5": null,
      "getError6": null,
      "getError7": null,
      "getError8": null,
      "getError9": null,
      "getSystemTime": null,
      "setSystemTime": null,
      "getKA5": null,
      "setKA5": null,
      "getKA5M2": null,
      "setKA5M2": null,
      "getKA5M3": null,
      "setKA5M3": null,
      "getKA6": null,
      "setKA6": null,
      "getKA6M2": null,
      "setKA6M2": null,
      "getKA6M3": null,
      "setKA6M3": null,
      "getKonfiWirkung_aufPumpe": null,
      "setKonfiWirkung_aufPumpe": null,
      "getKA3_KonfiFrostgrenzeM1_GWG": null,
      "setKA3_KonfiFrostgrenzeM1_GWG": null,
      "getKA3_KonfiFrostgrenzeM2_GWG": null,
      "setKA3_KonfiFrostgrenzeM2_GWG": null,
      "setPumpeStatusZirku": null,
      "setTimerM1Mo": null,
      "setTimerM1Di": null,
      "setTimerM1Mi": null,
      "setTimerM1Do": null,
      "setTimerM1Fr": null,
      "setTimerM1Sa": null,
      "setTimerM1So": null,
      "setTimerM2Mo": null,
      "setTimerM2Di": null,
      "setTimerM2Mi": null,
      "setTimerM2Do": null,
      "setTimerM2Fr": null,
      "setTimerM2Sa": null,
      "setTimerM2So": null,
      "setTimerWWMo": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWMo": "An:$1  Aus:$2\n"}},
      "setTimerWWDi": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWDi": "An:$1  Aus:$2\n"}},
      "setTimerWWMi": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWMi": "An:$1  Aus:$2\n"}},
      "setTimerWWDo": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWDo": "An:$1  Aus:$2\n"}},
      "setTimerWWFr": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWFr": "An:$1  Aus:$2\n"}},
      "setTimerWWSa": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWSa": "An:$1  Aus:$2\n"}},
      "setTimerWWSo": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerWWSo": "An:$1  Aus:$2\n"}},
      "setTimerZirkuMo": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuMo": "An:$1  Aus:$2\n"}},
      "setTimerZirkuDi": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuDi": "An:$1  Aus:$2\n"}},
      "setTimerZirkuMi": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuMi": "An:$1  Aus:$2\n"}},
      "setTimerZirkuDo": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuDo": "An:$1  Aus:$2\n"}},
      "setTimerZirkuFr": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuFr": "An:$1  Aus:$2\n"}},
      "setTimerZirkuSa": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuSa": "An:$1  Aus:$2\n"}},
      "setTimerZirkuSo": {"(\\d+:\\d+) +(\\d+:\\d+)": {"getTimerZirkuSo": "An:$1  Aus:$2\n"}},
      "getDevType": null,
      "getCtrlId": null,
      "getInventory": null,
      "getInvCodePlug": null,
      "getPanelSWIndex": null,
      "getKsCardType": null,
      "getAnlagenschema": null,
      "getUmschaltventil": null,
      "setUmschaltventil": null
    };
  }

  build() {
    return this.commands;
  }

  withCommand(command, value) {
    if (!this.commands.hasOwnProperty(command)) {
      throw new Error("Unknown command " + command)
    }

    this.commands[command] = value;
    return this;
  }
}
